// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VExtractor.Models.DataBase
{
    public partial class ecn_EnableDisable_Foreign_KeysResult
    {
    }
}
