// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnArreport
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Header { get; set; }

    public string Footer { get; set; }

    public int ObjectId { get; set; }

    public DateTime ScheduleTime { get; set; }

    public int ScheduleType { get; set; }

    public bool ScheduleDayMonday { get; set; }

    public bool ScheduleDayTuesday { get; set; }

    public bool ScheduleDayWednesday { get; set; }

    public bool ScheduleDayThursday { get; set; }

    public bool ScheduleDayFriday { get; set; }

    public bool ScheduleDaySaturday { get; set; }

    public bool ScheduleDaySunday { get; set; }

    public bool ScheduleMonthJanuary { get; set; }

    public bool ScheduleMonthFebruary { get; set; }

    public bool ScheduleMonthMarch { get; set; }

    public bool ScheduleMonthApril { get; set; }

    public bool ScheduleMonthMay { get; set; }

    public bool ScheduleMonthJune { get; set; }

    public bool ScheduleMonthJuly { get; set; }

    public bool ScheduleMonthAugust { get; set; }

    public bool ScheduleMonthSpetember { get; set; }

    public bool ScheduleMonthOctober { get; set; }

    public bool ScheduleMonthNovember { get; set; }

    public bool ScheduleMonthDecember { get; set; }

    public int ScheduleMonthDayToRun { get; set; }

    public DateTime? NextRun { get; set; }

    public DateTime? RunningSince { get; set; }
}