// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnArreportGraphLink
{
    public byte CompanyId { get; set; }

    public int ArreportId { get; set; }

    public int ArgraphId { get; set; }

    public int GraphOrder { get; set; }

    public string PreText { get; set; }

    public string PostText { get; set; }
}