// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnArdataSourceEventDatum
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int ArgraphId { get; set; }

    public string Name { get; set; }

    public int DeviceId { get; set; }

    public int DataPointId { get; set; }

    public int EventTypeId { get; set; }

    public int ArtransformationId { get; set; }

    public string SeriesType { get; set; }

    public int? XaxisDataSourceEventDataId { get; set; }
}