// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnApplicationFeature
{
    public string Name { get; set; }

    public byte CompanyId { get; set; }

    public string DisplayName { get; set; }

    public int ObjectId { get; set; }

    public int ApplicationFeatureGroupId { get; set; }
}