// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnConverterDeviceTypeLink
{
    public byte CompanyId { get; set; }

    public int ConverterId { get; set; }

    public int DeviceTypeTechnicalIdentificationAddress { get; set; }
}