// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnCompany
{
    public byte Id { get; set; }

    public string Name { get; set; }

    public string ConverterName { get; set; }

    public string Assembly { get; set; }

    public int DefaultCultureId { get; set; }

    public string Css { get; set; }

    public byte[] Image1 { get; set; }

    public byte[] Image2 { get; set; }

    public byte[] Image3 { get; set; }

    public string DesignSettingsXml { get; set; }

    public int RefrehTimeoutForEventStatusTray { get; set; }

    public int DefaultUserGroupId { get; set; }

    public int UndefinedStatusTypeId { get; set; }

    public string McdialogFzguser { get; set; }

    public string McdialogFzgpassword { get; set; }

    public int ScheduleActionTimeoutMin { get; set; }

    public string McdnotificationSmssender { get; set; }

    public string McdnotificationFaxSender { get; set; }

    public string McdnotificationEmailSender { get; set; }

    public int? McdfallBackDeviceId { get; set; }

    public int? NotificationRetries { get; set; }

    public int? NotificationType { get; set; }

    public string SmtprelayServer { get; set; }

    public string SmtpuserMailingsFromAddress { get; set; }

    public string Smtpuser { get; set; }

    public string Smtppassword { get; set; }

    public int DefaultDeviceGroupId { get; set; }

    public virtual ICollection<EcnEventGroupMasterDataCache> EcnEventGroupMasterDataCaches { get; set; } = new List<EcnEventGroupMasterDataCache>();

    public virtual ICollection<EcnEventGroupValueCache> EcnEventGroupValueCaches { get; set; } = new List<EcnEventGroupValueCache>();

    public virtual ICollection<VsmDeviceBrowserImage> VsmDeviceBrowserImages { get; set; } = new List<VsmDeviceBrowserImage>();

    public virtual ICollection<VsmDeviceDocument> VsmDeviceDocuments { get; set; } = new List<VsmDeviceDocument>();

    public virtual ICollection<VsmDeviceImage> VsmDeviceImages { get; set; } = new List<VsmDeviceImage>();

    public virtual ICollection<VsmEventTypeConversion> VsmEventTypeConversions { get; set; } = new List<VsmEventTypeConversion>();

    public virtual ICollection<VsmHydraulicCalibrationConfig> VsmHydraulicCalibrationConfigs { get; set; } = new List<VsmHydraulicCalibrationConfig>();

    public virtual ICollection<VsmRadiatorType> VsmRadiatorTypes { get; set; } = new List<VsmRadiatorType>();

    public virtual ICollection<VsmRadiatorValveManufacturer> VsmRadiatorValveManufacturers { get; set; } = new List<VsmRadiatorValveManufacturer>();

    public virtual ICollection<VsmShoppingCart> VsmShoppingCarts { get; set; } = new List<VsmShoppingCart>();
}