// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnConfirmationHistory
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int? NotificationId { get; set; }

    public int? MediaTypeId { get; set; }

    public string Message { get; set; }

    public DateTime? ConfirmationTime { get; set; }

    public int? UserId { get; set; }

    public string ConfimationAddress { get; set; }
}