// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnConfig
{
    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public string Value { get; set; }

    public string Options { get; set; }

    public string Path { get; set; }

    public string DataType { get; set; }

    public string Description { get; set; }
}