// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnDeviceTypeNotificationLink
{
    public int NotificationId { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceTypeId { get; set; }

    public int DataPointTypeId { get; set; }

    public int EventTypeId { get; set; }

    public int EventValueTypeId { get; set; }

    public string MatchValue { get; set; }

    public string SqlmatchValue { get; set; }

    public int DataPointTypeKeyId { get; set; }
}