// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnDeviceTypeKey
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceTypeId { get; set; }

    public int DataPointTypeId { get; set; }

    public string DataPointName { get; set; }

    public string DataPointAddress { get; set; }
}