// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnDatapointType
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int StatusEventTypeId { get; set; }

    public string Address { get; set; }

    public virtual VsmDatapointTypeExtension VsmDatapointTypeExtension { get; set; }

    public virtual ICollection<VsmDatapointTypeGroupDatapointTypeLink> VsmDatapointTypeGroupDatapointTypeLinks { get; set; } = new List<VsmDatapointTypeGroupDatapointTypeLink>();
}