// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnDeviceCommStatus
{
    public int Id { get; set; }

    public int CompanyId { get; set; }

    public int OuId { get; set; }

    public int DeviceId { get; set; }

    public int Status { get; set; }
}