// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnDisplayCondition
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public int ConditionGroupId { get; set; }

    public int EventTypeIdCondition { get; set; }

    public int EventTypeValueCondition { get; set; }

    public string Description { get; set; }

    public int Condition { get; set; }

    public double? ConditionValue { get; set; }
}