// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnDeviceTree
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int UserGroupId { get; set; }

    public string Name { get; set; }

    public int ParentId { get; set; }

    public int? OrderIndexInNode { get; set; }

    public int? NodeLevel { get; set; }

    public int? OrderIndex { get; set; }

    public int? DeviceId { get; set; }

    public string AbsolutePosition { get; set; }
}