// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnDevice
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public int DeviceTypeId { get; set; }

    public string Description { get; set; }

    public string ConnectionAdress { get; set; }

    public int Tcpport { get; set; }

    public int ConnectionTypeId { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string Serial { get; set; }

    public int StatusDataPointId { get; set; }

    public string InformationDataSetXml { get; set; }

    public string Location { get; set; }

    public string Street { get; set; }

    public string Plz { get; set; }

    public string City { get; set; }

    public string CustomerDescription { get; set; }

    public bool Active { get; set; }

    public bool Deleted { get; set; }

    public int InactivityTimeout { get; set; }

    public int? McdialogDeviceId { get; set; }

    public int? McdialogRoleId { get; set; }

    public bool CallbackEnabled { get; set; }

    public int? CallbackLatency { get; set; }

    public string AppLogin { get; set; }

    public string AppPassword { get; set; }

    public int RoutineCallTypeId { get; set; }

    public int? RoutinecallIntervall { get; set; }

    public DateTime? RoutinecallStartDate { get; set; }

    public int ObjectId { get; set; }

    public string ConverterParameter { get; set; }

    public DateTime LastModified { get; set; }

    public bool UpdateLock { get; set; }

    public virtual ICollection<EcnEventGroupMasterDataCache> EcnEventGroupMasterDataCaches { get; set; } = new List<EcnEventGroupMasterDataCache>();

    public virtual ICollection<EcnEventGroupValueCache> EcnEventGroupValueCaches { get; set; } = new List<EcnEventGroupValueCache>();

    public virtual ICollection<VsmDeviceDocument> VsmDeviceDocuments { get; set; } = new List<VsmDeviceDocument>();

    public virtual VsmDeviceImage VsmDeviceImage { get; set; }

    public virtual ICollection<VsmEquipment> VsmEquipments { get; set; } = new List<VsmEquipment>();

    public virtual ICollection<VsmEventTypeConversion> VsmEventTypeConversions { get; set; } = new List<VsmEventTypeConversion>();

    public virtual ICollection<VsmHydraulicCalibrationConfig> VsmHydraulicCalibrationConfigs { get; set; } = new List<VsmHydraulicCalibrationConfig>();

    public virtual ICollection<VsmOperationsDiary> VsmOperationsDiaries { get; set; } = new List<VsmOperationsDiary>();

    public virtual ICollection<VsmShoppingCart> VsmShoppingCarts { get; set; } = new List<VsmShoppingCart>();
}