// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnDeviceScheduleLog
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public string Message { get; set; }

    public bool Succesful { get; set; }
}