// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEventValueType
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public int? EnumAddressValue { get; set; }

    public string EnumReplaceValue { get; set; }

    public int StatusTypeId { get; set; }

    public string Unit { get; set; }

    public string DataType { get; set; }

    public double? Stepping { get; set; }

    public int? ValuePrecision { get; set; }

    public double? LowerBorder { get; set; }

    public double? UpperBorder { get; set; }

    public int? Length { get; set; }

    public string Description { get; set; }

    public virtual ICollection<EcnEventGroupValueCache> EcnEventGroupValueCaches { get; set; } = new List<EcnEventGroupValueCache>();
}