// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEventInstanceValue
{
    public int EventInstanceId { get; set; }

    public DateTime EventTime { get; set; }

    public float EventValue { get; set; }

    public virtual EcnEventInstance EventInstance { get; set; }
}