// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEventTypeAdditionalInfo
{
    public byte CompanyId { get; set; }

    public int EventTypeId { get; set; }

    public long Comment { get; set; }

    public string PicturePath { get; set; }
}