// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEventLogCurrentEvent
{
    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int DataPointId { get; set; }

    public int EventTypeId { get; set; }

    public long EventLogId { get; set; }

    public DateTime LastChange { get; set; }

    public DateTime LastEventReceivedTime { get; set; }
}