// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEventGroupMasterDataCache
{
    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int DataPointId { get; set; }

    public string RootEntrance { get; set; }

    public int EventTypeGroupId { get; set; }

    public int? EventTypeGroupOrderIndex { get; set; }

    public int EventTypeId { get; set; }

    public int? EventTypeOrderIndex { get; set; }

    public bool Display { get; set; }

    public virtual EcnCompany Company { get; set; }

    public virtual EcnDataPoint EcnDataPoint { get; set; }

    public virtual EcnDevice EcnDevice { get; set; }

    public virtual EcnEventTypeGroup EcnEventTypeGroup { get; set; }
}