// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEventInstance
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int DatapointId { get; set; }

    public int EventTypeId { get; set; }

    public string Unit { get; set; }

    public virtual ICollection<EcnEventInstanceValue> EcnEventInstanceValues { get; set; } = new List<EcnEventInstanceValue>();
}