// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnExportHistory
{
    public int ExportRunId { get; set; }

    public byte CompanyId { get; set; }

    public string TableName { get; set; }

    public string IdName { get; set; }

    public int IdValue { get; set; }

    public string Id2Name { get; set; }

    public int Id2Value { get; set; }

    public DateTime Date { get; set; }

    public bool Inserted { get; set; }

    public bool Deleted { get; set; }

    public string Name { get; set; }
}