// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEventTypeGroupTree
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int RootEventTypeGroupTreeId { get; set; }

    public int EventTypeGroupId { get; set; }

    public int ParentId { get; set; }

    public int OrderIndex { get; set; }
}