// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEventTypeGroup
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int ObjectGroupId { get; set; }

    public int ParentId { get; set; }

    public bool EntrancePoint { get; set; }

    public string Address { get; set; }

    public int DeviceTypeId { get; set; }

    public int DataPointTypeId { get; set; }

    public int OrderIndex { get; set; }

    public virtual ICollection<EcnEventGroupMasterDataCache> EcnEventGroupMasterDataCaches { get; set; } = new List<EcnEventGroupMasterDataCache>();

    public virtual VsmEventTypeGroupExtension VsmEventTypeGroupExtension { get; set; }
}