// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnExport
{
    public byte CompanyId { get; set; }

    public DateTime Date { get; set; }

    public int UserId { get; set; }

    public string TableName { get; set; }

    public int Id { get; set; }

    public int Id2 { get; set; }

    public string Name { get; set; }
}