// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnEscalationNotificationLink
{
    public byte CompanyId { get; set; }

    public int EscalationId { get; set; }

    public int NotificationId { get; set; }
}