// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnExportRun
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public DateTime Date { get; set; }

    public bool Success { get; set; }
}