// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnMaintenance
{
    public string Category { get; set; }

    public string Type { get; set; }

    public string Property { get; set; }

    public string Value { get; set; }

    public DateTime CreateDate { get; set; }

    public string Description { get; set; }
}