// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnNotificationAddress
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int UserId { get; set; }

    public int? MediaTypeId { get; set; }

    public string TargetAddress { get; set; }

    public int? Activated { get; set; }
}