// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnNotificationTime
{
    public int Id { get; set; }

    public int NotificationId { get; set; }

    public string WeekDayId { get; set; }

    public string StartTime { get; set; }

    public string EndTime { get; set; }

    public byte CompanyId { get; set; }
}