// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnNotificationHistory
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int? DeviceId { get; set; }

    public string TargetAddress { get; set; }

    public int? MediaTypeId { get; set; }

    public int? NotificationId { get; set; }

    public string ConfirmationId { get; set; }

    public string Message { get; set; }

    public string ToDo { get; set; }

    public DateTime? CreatedTime { get; set; }

    public DateTime? ExecutionTime { get; set; }

    public int? NotificationTypeId { get; set; }

    public short? ExecutionStatus { get; set; }

    public int? NumberOfRetries { get; set; }

    public string ErrorText { get; set; }

    public DateTime? ConfirmationTime { get; set; }

    public long? EventLogId { get; set; }

    public int EscalationLevel { get; set; }

    public int EscalationId { get; set; }

    public int McdnotificationState { get; set; }

    public int Timeout { get; set; }

    public int UserId { get; set; }
}