// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnObjectObjectgroupLink
{
    public byte CompanyId { get; set; }

    public int ObjectId { get; set; }

    public int ObjectGroupId { get; set; }
}