// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnPermissionValue
{
    public byte Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }
}