// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnRawDataError
{
    public long Id { get; set; }

    public byte CompanyId { get; set; }

    public string Ipaddress { get; set; }

    public DateTime ArrivalTimeStamp { get; set; }

    public byte[] RawData { get; set; }

    public int? DeviceId { get; set; }

    public string DeviceSerial { get; set; }
}