// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnReplacement
{
    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int DatapointId { get; set; }

    public string TableName { get; set; }

    public string TablePkfieldName { get; set; }

    public string TablePkvalue { get; set; }

    public string TableReplacementFieldName { get; set; }

    public string ReplacementValue { get; set; }
}