// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnStatusType
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public bool ShowInEventTray { get; set; }

    public byte[] Image { get; set; }

    public int SortOrder { get; set; }

    public virtual ICollection<EcnEventGroupValueCache> EcnEventGroupValueCaches { get; set; } = new List<EcnEventGroupValueCache>();
}