// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnTableExtension
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string TableName { get; set; }

    public string FieldName { get; set; }

    public string PkFields { get; set; }

    public byte[] InternalDefaultValue { get; set; }

    public int InternalDataType { get; set; }

    public string OptionsValue { get; set; }

    public string Label { get; set; }
}