// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnTrendViewChannel
{
    /// <summary>
    /// This field holds the link to table/field ecnTrendView.ID.
    /// </summary>
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int OuId { get; set; }

    public int TrendViewId { get; set; }

    public int DataPointId { get; set; }

    public int EventTypeId { get; set; }

    public int ChannelOrder { get; set; }

    public int ChannelColor { get; set; }
}