// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnTableExtensionValue
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int RefId { get; set; }

    public string PkValue { get; set; }

    public byte[] InternalValue { get; set; }

    public int PkId => int.Parse(PkValue.Split(";").First());
    public int PkCompanyId => int.Parse(PkValue.Split(";").Last());
}