// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnTrendConfig
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int OuId { get; set; }

    public int TrendType { get; set; }

    public int DeviceId { get; set; }

    public int DataPointId { get; set; }

    public string Description { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? StopTime { get; set; }

    public int Timescale { get; set; }
}