// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnTranslation
{
    public string TargetName { get; set; }

    public string Culture { get; set; }

    public string Translation { get; set; }

    public int? CreateUserId { get; set; }

    public DateTime? CreateDate { get; set; }
}