// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnUser
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public int AuthentificationTypeId { get; set; }

    public int? RoleId { get; set; }

    public string Password { get; set; }

    public int CultureId { get; set; }

    public bool Gender { get; set; }

    public string Title { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Street { get; set; }

    public string CityCode { get; set; }

    public string City { get; set; }

    public string Phone { get; set; }

    public string Mobile { get; set; }

    public string Fax { get; set; }

    public string EMail { get; set; }

    public string Annotation { get; set; }

    public bool Deleted { get; set; }

    public int ObjectId { get; set; }

    public virtual ICollection<VsmOperationsDiary> VsmOperationsDiaries { get; set; } = new List<VsmOperationsDiary>();

    public virtual VsmUserExtension VsmUserExtension { get; set; }
}