// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnUpdateDefinition
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string MajorSoftwareVersion { get; set; }

    public string MinorSoftwareVersion { get; set; }

    public string UsingIdentification { get; set; }

    public int DeviceTypeId { get; set; }

    public string ConnectionString { get; set; }

    public DateTime CreateTime { get; set; }

    public int CreatorId { get; set; }

    public DateTime ReleaseTime { get; set; }

    public int ReleaserId { get; set; }

    public bool Released { get; set; }
}