// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class EcnViewEventTypeGroupHierarchy
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int ObjectGroupId { get; set; }

    public int ParentId { get; set; }

    public bool EntrancePoint { get; set; }

    public string Address { get; set; }

    public int DeviceTypeId { get; set; }

    public int DataPointTypeId { get; set; }

    public int OrderIndex { get; set; }

    public string Path { get; set; }

    public string RootAddress { get; set; }

    public bool IsRootGroup { get; set; }

    public int RootId { get; set; }
}