// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using VExtractor.Helper;

namespace VExtractor.Models.DataBase;

public partial class VDataBase : DbContext
{
    public VDataBase()
    {
    }

    public VDataBase(DbContextOptions<VDataBase> options)
        : base(options)
    {
    }

    public virtual DbSet<EcnCulture> EcnCultures { get; set; }

    public virtual DbSet<EcnDataPointTypeEventTypeLink> EcnDataPointTypeEventTypeLinks { get; set; }

    public virtual DbSet<EcnDatapointType> EcnDatapointTypes { get; set; }

    public virtual DbSet<EcnDisplayCondition> EcnDisplayConditions { get; set; }

    public virtual DbSet<EcnDisplayConditionGroup> EcnDisplayConditionGroups { get; set; }

    public virtual DbSet<EcnEventType> EcnEventTypes { get; set; }

    public virtual DbSet<EcnEventTypeEventTypeGroupLink> EcnEventTypeEventTypeGroupLinks { get; set; }

    public virtual DbSet<EcnEventTypeEventValueTypeLink> EcnEventTypeEventValueTypeLinks { get; set; }

    public virtual DbSet<EcnEventTypeGroup> EcnEventTypeGroups { get; set; }

    public virtual DbSet<EcnEventValueType> EcnEventValueTypes { get; set; }

    public virtual DbSet<EcnTableExtension> EcnTableExtensions { get; set; }

    public virtual DbSet<EcnTableExtensionValue> EcnTableExtensionValues { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            // The normal source is a SQLite file produced by SourceLoader from the installer's
            // definition file. A SQL Server holding an installed copy of the database still
            // works when VEXTRACTOR_SOURCE_DB is not set.
            var sourceDb = Environment.GetEnvironmentVariable("VEXTRACTOR_SOURCE_DB");
            if (!string.IsNullOrWhiteSpace(sourceDb))
            {
                optionsBuilder.UseSqlite($"Data Source={sourceDb}");
                return;
            }
            var connectionString = DataHelper.GetConnectionString();
            SqlServerDbContextOptionsExtensions.UseSqlServer(optionsBuilder, connectionString, o => o.UseCompatibilityLevel(120));
        }
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("VEXTRACTOR_SOURCE_DB")))
            modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.Entity<EcnCulture>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnCulture");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<EcnDataPointTypeEventTypeLink>(entity =>
        {
            entity.HasKey(e => new { e.CompanyId, e.DataPointTypeId, e.EventTypeId });

            entity.ToTable("ecnDataPointTypeEventTypeLink");
        });

        modelBuilder.Entity<EcnDatapointType>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnDatapointType");

            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<EcnDisplayCondition>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnDisplayCondition");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<EcnDisplayConditionGroup>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnDisplayConditionGroup");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<EcnEventType>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnEventType");

            entity.HasIndex(e => e.CompanyId, "CompanyIdx");

            entity.HasIndex(e => new { e.CompanyId, e.Address }, "IX_ecnEventType_CompanyId_Address");

            entity.HasIndex(e => new { e.Id, e.CompanyId }, "_dta_index_ecnEventType_23_365244356__K1_K2_3_4_5_6_7_8_9_10_11_12_13");

            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Conversion)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DefaultValue)
                .HasMaxLength(1024)
                .IsUnicode(false);
            entity.Property(e => e.Filtercriterion).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ObjectId).HasDefaultValue(-1);
            entity.Property(e => e.Reportingcriterion).HasDefaultValue(true);
            entity.Property(e => e.Url)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("URL");
        });

        modelBuilder.Entity<EcnEventTypeEventTypeGroupLink>(entity =>
        {
            entity.HasKey(e => new { e.CompanyId, e.EventTypeId, e.EventTypeGroupId });

            entity.ToTable("ecnEventTypeEventTypeGroupLink");
        });

        modelBuilder.Entity<EcnEventTypeEventValueTypeLink>(entity =>
        {
            entity.HasKey(e => new { e.CompanyId, e.EventTypeId, e.EventValueId });

            entity.ToTable("ecnEventTypeEventValueTypeLink");

            entity.HasIndex(e => new { e.CompanyId, e.EventTypeId }, "_dta_index_ecnEventTypeEventValueTypeLink_23_421576540__K1_K2");
        });

        modelBuilder.Entity<EcnEventTypeGroup>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnEventTypeGroup");

            entity.HasIndex(e => new { e.CompanyId, e.DeviceTypeId, e.DataPointTypeId }, "IX_DatapointTypeGroupIndex");

            entity.HasIndex(e => new { e.CompanyId, e.ParentId }, "IX_ecnEventTypeGroupHierarchy");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ObjectGroupId).HasDefaultValue(-1);
        });

        modelBuilder.Entity<EcnEventValueType>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnEventValueType");

            entity.HasIndex(e => e.CompanyId, "CompanyIdIdx");

            entity.HasIndex(e => new { e.Id, e.CompanyId }, "_dta_index_ecnEventValueType_23_525244926__K1_K2_3_4_5_6_7_8_9_10_11_12_13_14");

            entity.Property(e => e.DataType)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.EnumReplaceValue)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Unit)
                .HasMaxLength(255)
                .IsUnicode(false);
        });

        modelBuilder.Entity<EcnTableExtension>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnTableExtension");

            entity.HasIndex(e => e.FieldName, "IX_ecnTableExtension_FieldName");

            entity.HasIndex(e => e.TableName, "IX_ecnTableExtension_TableName");

            entity.HasIndex(e => new { e.TableName, e.FieldName }, "IX_ecnTableExtension_TableNameFieldName");

            entity.Property(e => e.FieldName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.InternalDefaultValue).IsRequired();
            entity.Property(e => e.Label).HasMaxLength(100);
            entity.Property(e => e.OptionsValue).IsUnicode(false);
            entity.Property(e => e.PkFields)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.TableName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<EcnTableExtensionValue>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.CompanyId });

            entity.ToTable("ecnTableExtensionValue");

            entity.HasIndex(e => new { e.CompanyId, e.RefId }, "IX_ecnTableExtensionValue_CompanyIdRefId");

            entity.HasIndex(e => new { e.CompanyId, e.RefId, e.PkValue }, "IX_ecnTableExtensionValue_CompanyIdRefIdPkValue");

            entity.Property(e => e.InternalValue).IsRequired();
            entity.Property(e => e.PkValue)
                .IsRequired()
                .HasMaxLength(150);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}