// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class View1
{
    public byte? CompanyId { get; set; }

    public int? EventType { get; set; }

    public int DataPointTypeId { get; set; }

    public int DataPoint { get; set; }

    public int DeviceId { get; set; }
}