// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmCfconnectionLog
{
    public long Id { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int ConnectionDirectionId { get; set; }

    public string DirectConnectionAddress { get; set; }

    public string CallbackConnectionAddress { get; set; }

    public int ConnectionStatusId { get; set; }

    public string ConnectionStatusText { get; set; }

    public DateTime CreateTime { get; set; }
}