// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmDeviceReadDatum
{
    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int DataPointId { get; set; }

    public int ReadDataStatusId { get; set; }
}