// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmDeviceBrowserImage
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string VsmImageId { get; set; }

    public string FileName { get; set; }

    public virtual EcnCompany Company { get; set; }
}