// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmDatapointTypeExtension
{
    public int DatapointTypeId { get; set; }

    public byte CompanyId { get; set; }

    public bool? Viaready { get; set; }

    public virtual EcnDatapointType EcnDatapointType { get; set; }
}