// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmDeviceDocument
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int Type { get; set; }

    public int RefId { get; set; }

    public string FileUrl { get; set; }

    public int UserId { get; set; }

    public string Name { get; set; }

    public string Remark { get; set; }

    public virtual EcnCompany Company { get; set; }

    public virtual EcnDevice EcnDevice { get; set; }
}