// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

/// <summary>
/// Tabelle für die Anlagenschemen.
/// </summary>
public partial class VsmDeviceSchema
{
    /// <summary>
    /// Id Feld des e-ControlNet aus der TAN Tabelle.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// CompanyId des Mandanten im e-ControlNet.
    /// </summary>
    public byte CompanyId { get; set; }

    /// <summary>
    /// DeviceId (Viessmann Anlagen Id) des e-ControlNet.
    /// </summary>
    public int DeviceId { get; set; }

    /// <summary>
    /// ImageURL aus der das Anlagenschema geladen werden kann.
    /// </summary>
    public string ImageUrl { get; set; }

    /// <summary>
    /// Aktualisierungsintervall des Anlagenschemas. Falls 0 (oder kleiner 0) gesetzt ist wird das Anlagenschema nicht aktualisiert.
    /// </summary>
    public int? UpdateCycle { get; set; }
}