// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmEquipmentReference
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Zeid { get; set; }

    public string SwindexFrom { get; set; }

    public string SwindexTo { get; set; }

    public string CodeAddress { get; set; }

    public int ValueType { get; set; }

    public byte[] Value { get; set; }

    public string PartNumber { get; set; }

    public virtual ICollection<VsmEquipment> VsmEquipments { get; set; } = new List<VsmEquipment>();
}