// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmEventTypeGroupExtension
{
    public int EventTypeGroupId { get; set; }

    public byte CompanyId { get; set; }

    public bool? IsForIphone { get; set; }

    public virtual EcnEventTypeGroup EcnEventTypeGroup { get; set; }
}