// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmEventTypeConversion
{
    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int DatapointId { get; set; }

    public int EventTypeId { get; set; }

    public string Unit { get; set; }

    public double? Factor { get; set; }

    public double? Offset { get; set; }

    public int ConversionType { get; set; }

    public virtual EcnCompany Company { get; set; }

    public virtual EcnDataPoint EcnDataPoint { get; set; }

    public virtual EcnDevice EcnDevice { get; set; }

    public virtual EcnEventType EcnEventType { get; set; }
}