// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmEquipment
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int? DataPointId { get; set; }

    public int? EquipmentReferenceId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string PartNumber { get; set; }

    public int Typ { get; set; }

    public bool Assigned { get; set; }

    public virtual EcnDataPoint EcnDataPoint { get; set; }

    public virtual EcnDevice EcnDevice { get; set; }

    public virtual VsmEquipmentReference VsmEquipmentReference { get; set; }
}