// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmHydraulicCalibrationRadiatorConfig
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int RoomId { get; set; }

    public int RadiatorId { get; set; }

    public int ValveId { get; set; }

    public int ActuatorId { get; set; }

    public double RequiredVolumeFlow { get; set; }

    public int RadiatorNumber { get; set; }

    public virtual ICollection<VsmHydraulicCalibrationResultValve> VsmHydraulicCalibrationResultValves { get; set; } = new List<VsmHydraulicCalibrationResultValve>();

    public virtual VsmHydraulicCalibrationRoomConfig VsmHydraulicCalibrationRoomConfig { get; set; }

    public virtual VsmRadiator VsmRadiator { get; set; }

    public virtual VsmRadiatorValve VsmRadiatorValve { get; set; }
}