// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmHydraulicCalibrationConfig
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public double ClimateZone { get; set; }

    public double Niveau { get; set; }

    public int DatapointId { get; set; }

    public int HeatingCircuitId { get; set; }

    public int Category { get; set; }

    public int? Type { get; set; }

    public int? Pump { get; set; }

    public string PartNo { get; set; }

    public virtual EcnCompany Company { get; set; }

    public virtual EcnDevice EcnDevice { get; set; }

    public virtual ICollection<VsmHydraulicCalibrationResult> VsmHydraulicCalibrationResults { get; set; } = new List<VsmHydraulicCalibrationResult>();

    public virtual ICollection<VsmHydraulicCalibrationRoomConfig> VsmHydraulicCalibrationRoomConfigs { get; set; } = new List<VsmHydraulicCalibrationRoomConfig>();
}