// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmHydraulicCalibrationRoomConfig
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int ConfigId { get; set; }

    public int RoomNumber { get; set; }

    public string Name { get; set; }

    public int HeatingDemand { get; set; }

    public bool IsRecalculated { get; set; }

    public virtual VsmHydraulicCalibrationConfig VsmHydraulicCalibrationConfig { get; set; }

    public virtual ICollection<VsmHydraulicCalibrationRadiatorConfig> VsmHydraulicCalibrationRadiatorConfigs { get; set; } = new List<VsmHydraulicCalibrationRadiatorConfig>();
}