// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmHydraulicCalibrationMeasurementResultStatus
{
    public int MeasurementId { get; set; }

    public byte CompanyId { get; set; }

    public int ResultValveId { get; set; }

    public bool ValveStatus { get; set; }

    public virtual VsmHydraulicCalibrationMeasurementResult VsmHydraulicCalibrationMeasurementResult { get; set; }

    public virtual VsmHydraulicCalibrationResultValve VsmHydraulicCalibrationResultValve { get; set; }
}