// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmHydraulicCalibrationResult
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int ConfigId { get; set; }

    public double MaxRequestedFlowTemperature { get; set; }

    public double Pitch { get; set; }

    public double RemainingPumpingHeight { get; set; }

    public double MaximumPumpSpeed { get; set; }

    public virtual VsmHydraulicCalibrationConfig VsmHydraulicCalibrationConfig { get; set; }

    public virtual ICollection<VsmHydraulicCalibrationMeasurementResult> VsmHydraulicCalibrationMeasurementResults { get; set; } = new List<VsmHydraulicCalibrationMeasurementResult>();

    public virtual ICollection<VsmHydraulicCalibrationResultValve> VsmHydraulicCalibrationResultValves { get; set; } = new List<VsmHydraulicCalibrationResultValve>();
}