// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmParameterSet
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int DatapointId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int DatapointTypeId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual ICollection<VsmParameterValue> VsmParameterValues { get; set; } = new List<VsmParameterValue>();
}