// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmParameterValue
{
    public int ParameterSetId { get; set; }

    public int TypeId { get; set; }

    public int ValueTypeId { get; set; }

    public byte[] Value { get; set; }

    public virtual VsmParameterSet ParameterSet { get; set; }
}