// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmRadiatorValve
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public int ManufacturerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Tganumber { get; set; }

    public virtual ICollection<VsmHydraulicCalibrationRadiatorConfig> VsmHydraulicCalibrationRadiatorConfigs { get; set; } = new List<VsmHydraulicCalibrationRadiatorConfig>();

    public virtual VsmRadiatorValveManufacturer VsmRadiatorValveManufacturer { get; set; }
}