// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmRadiatorType
{
    public int Id { get; set; }

    public byte CompanyId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool UseDimensionZ { get; set; }

    public string DimensionXunit { get; set; }

    public string DimensionYunit { get; set; }

    public string DimensionZunit { get; set; }

    public string DimensionXname { get; set; }

    public string DimensionYname { get; set; }

    public string DimensionZname { get; set; }

    public virtual EcnCompany Company { get; set; }

    public virtual ICollection<VsmRadiator> VsmRadiators { get; set; } = new List<VsmRadiator>();
}