// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStsparepartDetail
{
    public string LanguageIsocode { get; set; }

    public string MaterialNumber { get; set; }

    public string MaterialShortText { get; set; }

    public string TranslationText { get; set; }

    public string CatalogText { get; set; }

    public string MaterialGroup { get; set; }

    public string MaterialType { get; set; }
}