// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStdocument
{
    public int Id { get; set; }

    public string LanguageIsocode { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public int DocumentType { get; set; }

    public string DocumentMimeType { get; set; }

    public string PrintNumber { get; set; }

    public int Status { get; set; }

    public virtual ICollection<VsmStdocumentDatapointTypeLink> VsmStdocumentDatapointTypeLinks { get; set; } = new List<VsmStdocumentDatapointTypeLink>();
}