// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStsparepart
{
    public int Id { get; set; }

    public int SalesOrganisationId { get; set; }

    public string PositionId { get; set; }

    public string PosMaterialNumber { get; set; }

    public string MaterialNumber { get; set; }

    public DateTime ValidFrom { get; set; }

    public DateTime ValidTo { get; set; }

    public string QuantityUnit { get; set; }

    public virtual VsmStsalesOrganisation SalesOrganisation { get; set; }
}