// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStdeviceSchema
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ImageUrl { get; set; }

    public int? UpdateCycle { get; set; }

    public string Description { get; set; }

    public virtual ICollection<VsmStdeviceSchemaEventTypeLink> VsmStdeviceSchemaEventTypeLinks { get; set; } = new List<VsmStdeviceSchemaEventTypeLink>();
}