// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStuser
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string UserEmail { get; set; }

    public bool SendNotification { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }
}