// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStdocumentDatapointTypeLink
{
    public int DocumentId { get; set; }

    public string MaterialNumber { get; set; }

    public string DatapointTypeAddress { get; set; }

    public virtual VsmStdocument Document { get; set; }
}