// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStsparepartList
{
    public int Id { get; set; }

    public int SalesOrganisationId { get; set; }

    public string DatapointTypeAddress { get; set; }

    public string MaterialNumber { get; set; }

    public string ImageUrl { get; set; }

    public virtual VsmStsalesOrganisation SalesOrganisation { get; set; }
}