// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStsalesOrganisation
{
    public int Id { get; set; }

    public string VkOrg { get; set; }

    public string Name { get; set; }

    public bool IsRelevant { get; set; }

    public virtual ICollection<VsmStproductCatalog> VsmStproductCatalogs { get; set; } = new List<VsmStproductCatalog>();

    public virtual ICollection<VsmStsparepartList> VsmStsparepartLists { get; set; } = new List<VsmStsparepartList>();

    public virtual ICollection<VsmStsparepart> VsmStspareparts { get; set; } = new List<VsmStsparepart>();
}