// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmStdeviceSchemaEventTypeLink
{
    public int DeviceSchemaId { get; set; }

    public int Pos { get; set; }

    public string DatapointTypeAddress { get; set; }

    public string EventTypeAddress { get; set; }

    public int PosX { get; set; }

    public int PosY { get; set; }

    public virtual VsmStdeviceSchema DeviceSchema { get; set; }
}