// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmUserExtension
{
    public int UserId { get; set; }

    public byte CompanyId { get; set; }

    public int? SalesOrganisationId { get; set; }

    public DateTime? LastReleaeNotesNotifiedDate { get; set; }

    public virtual EcnUser EcnUser { get; set; }
}