// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmViewHydraulicCalibrationHeatingCircuitType
{
    public int DatapointTypeId { get; set; }

    public byte CompanyId { get; set; }

    public string DatapointTypeAddress { get; set; }

    public int EventTypeGroupId { get; set; }

    public string EventTypeGroupAddress { get; set; }

    public string EventTypeGroupName { get; set; }

    public string EventTypeGroupPath { get; set; }

    public string TableName { get; set; }

    public byte[] LogicalMapping { get; set; }
}