// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmViewDefaultDatum
{
    public string EventTypeGroupRootAddress { get; set; }

    public string EventTypeGroupAddress { get; set; }

    public byte CompanyId { get; set; }

    public int DataPointTypeId { get; set; }

    public string EventTypeGroupDescription { get; set; }

    public int DeviceTypeId { get; set; }

    public bool EntrancePoint { get; set; }

    public int EventTypeGroupId { get; set; }

    public string EventTypeGroupName { get; set; }

    public int EventTypeGroupOrderIndex { get; set; }

    public int EventTypeGroupParentId { get; set; }

    public string EventTypeGroupPath { get; set; }

    public string RootAddress { get; set; }

    public int? EventTypeOrderIndex { get; set; }

    public string EventTypeAddress { get; set; }

    public string EventTypeConversion { get; set; }

    public string EventTypeDefaultValue { get; set; }

    public string EventTypeDescription { get; set; }

    public bool? EnumType { get; set; }

    public bool? Filtercriterion { get; set; }

    public int? EventTypeId { get; set; }

    public string EventTypeName { get; set; }

    public int? EventTypePriority { get; set; }

    public bool? Reportingcriterion { get; set; }

    public int? Type { get; set; }

    public string Url { get; set; }

    public string DataType { get; set; }

    public string EventValueTypeDescription { get; set; }

    public int? EnumAddressValue { get; set; }

    public string EnumReplaceValue { get; set; }

    public int? EventValueTypeId { get; set; }

    public int? Length { get; set; }

    public double? LowerBorder { get; set; }

    public string EventValueTypeName { get; set; }

    public int? StatusTypeId { get; set; }

    public double? Stepping { get; set; }

    public string Unit { get; set; }

    public double? UpperBorder { get; set; }

    public int? ValuePrecision { get; set; }

    public long? Comment { get; set; }

    public byte[] CodeLevelArea { get; set; }

    public byte[] EventTypeByteLength { get; set; }

    public bool IsRootGroup { get; set; }
}