// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmViewHydraulicCalibrationHeatingCircuit
{
    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int DatapointId { get; set; }

    public int DataPointTypeId { get; set; }

    public string DatapointTypeAddress { get; set; }

    public int EventTypeGroupId { get; set; }

    public string EventTypeGroupAddress { get; set; }

    public string EventTypeGroupName { get; set; }

    public string EventTypeGroupPath { get; set; }

    public byte[] LogicalMapping { get; set; }

    public string NameReplacement { get; set; }
}