// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmViewHydraulicCalibrationResult
{
    public int ConfigId { get; set; }

    public byte CompanyId { get; set; }

    public int DeviceId { get; set; }

    public int DatapointId { get; set; }

    public int HeatingCircuitId { get; set; }

    public int ResultId { get; set; }

    public double MaxRequestedFlowTemperature { get; set; }

    public double Pitch { get; set; }

    public double RemainingPumpingHeight { get; set; }

    public double MaximumPumpSpeed { get; set; }

    public int ResultValveId { get; set; }

    public int ValveNumber { get; set; }

    public double ValvePressureLoss { get; set; }

    public string ValveDefaultSetting { get; set; }

    public int RadiatorConfigId { get; set; }

    public int ActuatorId { get; set; }

    public double ValveRequiredVolumeFlow { get; set; }

    public int MeasurementId { get; set; }

    public int MeasurementNumber { get; set; }

    public DateTime MeasurementDateTime { get; set; }

    public int MeasurementPressureDifference { get; set; }

    public int MeasurementVolumeFlow { get; set; }

    public bool ValveStatus { get; set; }

    public int RadiatorNumber { get; set; }

    public double ClimateZone { get; set; }

    public double Niveau { get; set; }

    public int Category { get; set; }

    public int? Type { get; set; }

    public int? Pump { get; set; }

    public int RoomConfigId { get; set; }

    public int RoomNumber { get; set; }

    public string RoomName { get; set; }

    public string PartNo { get; set; }
}