// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VExtractor.Models.DataBase;

public partial class VsmViewHydraulicCalibrationEvent
{
    public long EventLogId { get; set; }

    public byte CompanyId { get; set; }

    public int EventTypeId { get; set; }

    public int EventValueTypeId { get; set; }

    public double? EventValueFloat { get; set; }

    public int? EventValueInt { get; set; }

    public string EventValueVarChar { get; set; }

    public string EventValueNtext { get; set; }

    public bool? EventValueBit { get; set; }

    public byte[] EventValueBinary { get; set; }

    public DateTime? EventValueDateTime { get; set; }

    public string Unit { get; set; }

    public string DataType { get; set; }

    public int DeviceId { get; set; }

    public int DataPointId { get; set; }

    public DateTime EventTime { get; set; }

    public int? EventPriority { get; set; }

    public int? StatusTypeId { get; set; }

    public DateTime EventReceivedTime { get; set; }

    public long EventLogDataGroupId { get; set; }

    public DateTime LastChange { get; set; }

    public DateTime LastEventReceivedTime { get; set; }

    public string EventTypeAddress { get; set; }
}